// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","id":"1"},"2":{"path":"/docs","id":"2"},"3":{"name":"home","path":"/index.html","id":"3"},"4":{"name":"product","path":"/product.html","id":"4"},"5":{"name":"detail","path":"/detail.html","id":"5"},"6":{"name":"about","path":"/about.html","id":"6"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__docs" */'@/pages/docs.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__home__index" */'@/pages/home/index.jsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__product__index" */'@/pages/product/index.jsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__detail__index" */'@/pages/detail/index.jsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__about__index" */'@/pages/about/index.jsx')),
},
  };
}
