// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/hou/work/limeet/src/models/detail';
import model_2 from '/Users/hou/work/limeet/src/models/home';
import model_3 from '/Users/hou/work/limeet/src/models/product';

export const models = {
model_1: { namespace: 'detail', model: model_1 },
model_2: { namespace: 'home', model: model_2 },
model_3: { namespace: 'product', model: model_3 },
} as const
