// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_2 from '/Users/hou/work/limeet/src/models/common';
import model_1 from '/Users/hou/work/limeet/src/models/categories';
import model_3 from '/Users/hou/work/limeet/src/models/productDetail';
import model_4 from '/Users/hou/work/limeet/src/models/productList';
import model_5 from '/Users/hou/work/limeet/src/.umi/plugin-initialState/@@initialState';

export const models = {
model_2: { namespace: 'common', model: model_2 },
model_1: { namespace: 'categories', model: model_1 },
model_3: { namespace: 'productDetail', model: model_3 },
model_4: { namespace: 'productList', model: model_4 },
model_5: { namespace: '@@initialState', model: model_5 },
} as const
